admin: 
  book:
    create: "Created success !"
    update: "Updated success !"
length:
  page: 10
  page_book: 12
picture:
  max_size: 5
  width: "200"
  height: "280"
  width_n: "320"
  height_n: "448"
image_type:
  - "jpg"
  - "jpeg"
  - "gif"
  - "png"
resize:
  - 400
  - 400
roles:
  - "admin"
  - "user"
setting:
  follow_type:
    - following
    - followers
  following: following
  followers: followers
requests_per_page: 10
title_length: 25
description_length: 30
reads:
  - "reading"
  - "read"
default_image:
  "/Book-cover-black.jpg"
week_back: 1
action_type:
  - "follow"
  - "unfollow"
  - "mark_read"
  - "mark_favorite"
  - "mark_unfavorite"
  - "write_review"
  - "write_comment"
